# Generated by Django 4.1.7 on 2023-02-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('aprovado', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=60, null=True)),
                ('anunciado', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=60, null=True)),
                ('período', models.DateField(blank=True, null=True)),
                ('tempo_indeterminado', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=60, null=True)),
            ],
        ),
    ]
