# Generated by Django 4.1.7 on 2023-02-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerais',
            name='período',
            field=models.DateField(blank=True, null=True, verbose_name='Período (MM/AAAA)'),
        ),
    ]
