# Generated by Django 4.1.7 on 2023-02-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_alter_gerais_período'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerais',
            name='comissão',
            field=models.CharField(blank=True, choices=[('Jeferson Oliveira', 'Jeferson Oliveira'), ('Elidomar Santos', 'Elidomar Santos'), ('Isac Diogo', 'Isac Diogo')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='gerais',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
