# Generated by Django 4.1.7 on 2023-02-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0004_remove_gerais_período_gerais_período_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerais',
            name='comissão',
        ),
        migrations.AddField(
            model_name='gerais',
            name='coordenador',
            field=models.CharField(blank=True, choices=[('Jeferson Oliveira', 'Jeferson Oliveira'), ('Elidomar Santos', 'Elidomar Santos'), ('Isac Diogo', 'Isac Diogo'), ('José Santana', 'José Santana'), ('Abel Correia', 'Abel Correia'), ('Geraldo Xavier', 'Geraldo Xavier')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='gerais',
            name='secretário',
            field=models.CharField(blank=True, choices=[('Jeferson Oliveira', 'Jeferson Oliveira'), ('Elidomar Santos', 'Elidomar Santos'), ('Isac Diogo', 'Isac Diogo'), ('José Santana', 'José Santana'), ('Abel Correia', 'Abel Correia'), ('Geraldo Xavier', 'Geraldo Xavier')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='gerais',
            name='serviço',
            field=models.CharField(blank=True, choices=[('Jeferson Oliveira', 'Jeferson Oliveira'), ('Elidomar Santos', 'Elidomar Santos'), ('Isac Diogo', 'Isac Diogo'), ('José Santana', 'José Santana'), ('Abel Correia', 'Abel Correia'), ('Geraldo Xavier', 'Geraldo Xavier')], max_length=60, null=True),
        ),
    ]
