# Generated by Django 4.1.7 on 2023-02-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0006_comissão_remove_gerais_coordenador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissão',
            name='serviço',
            field=models.CharField(blank=True, choices=[('Jeferson Oliveira', 'Jeferson Oliveira'), ('Elidomar Santos', 'Elidomar Santos'), ('Isac Diogo', 'Isac Diogo'), ('José Santana', 'José Santana'), ('Abel Correia', 'Abel Correia'), ('Geraldo Xavier', 'Geraldo Xavier')], max_length=60, null=True, verbose_name='Superintendente de Serviço'),
        ),
    ]
