# Generated by Django 4.1.7 on 2023-02-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0007_alter_comissão_serviço'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerais',
            name='período_inicial',
        ),
        migrations.AddField(
            model_name='gerais',
            name='ano_final',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='gerais',
            name='ano_inicial',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='gerais',
            name='mês_Final',
            field=models.CharField(blank=True, choices=[('\tJaneiro\t', '\tJaneiro\t'), ('\tFevereiro\t', '\tFevereiro\t'), ('\tMarço\t', '\tMarço\t'), ('\tAbril\t', '\tAbril\t'), ('\tMaio\t', '\tMaio\t'), ('\tJunho\t', '\tJunho\t'), ('\tJulho\t', '\tJulho\t'), ('\tAgosto\t', '\tAgosto\t'), ('\tSetembro\t', '\tSetembro\t'), ('\tOutubro\t', '\tOutubro\t'), ('\tNovembro\t', '\tNovembro\t'), ('\tDezembro\t', '\tDezembro\t')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='gerais',
            name='mês_Inicial',
            field=models.CharField(blank=True, choices=[('\tJaneiro\t', '\tJaneiro\t'), ('\tFevereiro\t', '\tFevereiro\t'), ('\tMarço\t', '\tMarço\t'), ('\tAbril\t', '\tAbril\t'), ('\tMaio\t', '\tMaio\t'), ('\tJunho\t', '\tJunho\t'), ('\tJulho\t', '\tJulho\t'), ('\tAgosto\t', '\tAgosto\t'), ('\tSetembro\t', '\tSetembro\t'), ('\tOutubro\t', '\tOutubro\t'), ('\tNovembro\t', '\tNovembro\t'), ('\tDezembro\t', '\tDezembro\t')], max_length=60, null=True),
        ),
    ]
